# 디버그 모드 빌드 후 firebase distribution 업로드
name: Debug - firebase

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Create google-services.json
      id: createGoogleService
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 필요하지 않지만 github actions 수행 중 실패해서 넣어 줌
    - name: Create local.properties
      id: createLocalProperties
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: users
        file: app/build/outputs/apk/debug/app-debug.apk
