# 디버그 모드 빌드 후 firebase distribution 업로드
name: Debug - firebase

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload artifact to Firebase App Distribution
      run: |
        INPUT_APPID=${{secrets.FIREBASE_APP_ID}}
        FIREBASE_TOKEN=${{secrets.FIREBASE_TOKEN}}
        INPUT_GROUPS="users"
        INPUT_FILE="app/build/outputs/apk/debug/app-debug.apk"
        RELEASE_NOTES="$(git log -1 --pretty=short)"
        firebase \
          appdistribution:distribute \
          "$INPUT_FILE" \
          --app "$INPUT_APPID" \
          --token "$FIREBASE_TOKEN" \
          --groups "$INPUT_GROUPS" \
          ${RELEASE_NOTES:+ --release-notes "${RELEASE_NOTES}"}
