# 릴리즈 빌드 후 playstore 업로드 (배포용)
name: Release - playstore

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Keystore file from Github Secrets
      env:
        KEYSTORE: ${{ secrets.UPLOAD_KEYSTORE_JKS_BASE64 }}
      run: |
        echo "$KEYSTORE" > ./keystore.b64
        base64 -d -i ./keystore.b64 > ./app/babo_keystore_2019.jks

    - name: Create local.properties
      id: createLocalProperties
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

    - name: Create google-services.json
      id: createGoogleService
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Release AAB
      id: buildRelease
      run: ./gradlew bundleRelease

    - name: Upload APK
      id: uploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/bundle/release/app-release.aab

    - name: Create service_account.json
      id: createServiceAccount
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
        
    - name: Deploy to Play Store
      id: deploy
      uses: r0adkll/upload-google-play@v1.0.19
      with:
        serviceAccountJson: service_account.json
        packageName: com.trueedu.project
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: internal
        status: completed
